// <auto-generated />
using System;
using MesWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesWEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910013841_AddPageAccessCounter")]
    partial class AddPageAccessCounter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MesWEB.Data.GrowthNoteItem", b =>
                {
                    b.Property<int>("CGNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CGNoteId"));

                    b.Property<string>("BottomInsulationComposition")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CrucibleCount")
                        .HasColumnType("int");

                    b.Property<string>("CrucibleName")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("CrystalGrowthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrystalLot")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int?>("CulletFeed")
                        .HasColumnType("int");

                    b.Property<string>("CulletLot1")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CulletLot2")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CulletLot3")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("DeltaT")
                        .HasColumnType("int");

                    b.Property<float?>("DopantAmount")
                        .HasColumnType("real");

                    b.Property<string>("Dopants")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<float?>("FirstRotationalSpeed")
                        .HasColumnType("real");

                    b.Property<string>("FurnaceCondition1")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("FurnaceCondition2")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("GravityCenterWC")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<TimeSpan?>("GrowthStartTime")
                        .HasColumnType("time");

                    b.Property<float?>("GrowthVoltage")
                        .HasColumnType("real");

                    b.Property<int?>("HeadDiameter")
                        .HasColumnType("int");

                    b.Property<string>("HeightPositionWC")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("InsideInsulationComposition")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<float?>("LastPullingSpeed")
                        .HasColumnType("real");

                    b.Property<float?>("LastRotationalSpeed")
                        .HasColumnType("real");

                    b.Property<string>("LiquidLevel")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("MachineName")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<float?>("NeckingVoltage")
                        .HasColumnType("real");

                    b.Property<string>("Operator")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("OutputCurrent")
                        .HasColumnType("int");

                    b.Property<int?>("OutputVoltage")
                        .HasColumnType("int");

                    b.Property<int?>("PelletFeed")
                        .HasColumnType("int");

                    b.Property<string>("PelletLot1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PelletLot2")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PelletLot3")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RingHeightPosition")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<float?>("SeedHeightPosition")
                        .HasColumnType("real");

                    b.Property<float?>("ShoulderEndPullingSpeed")
                        .HasColumnType("real");

                    b.Property<float?>("ShoulderEndRotationalSpeed")
                        .HasColumnType("real");

                    b.Property<TimeSpan?>("ShoulderEndTime")
                        .HasColumnType("time");

                    b.Property<float?>("StartPullingSpeed")
                        .HasColumnType("real");

                    b.Property<int?>("TailDiameter")
                        .HasColumnType("int");

                    b.Property<string>("UsingDisk")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("ppm")
                        .HasColumnType("int");

                    b.HasKey("CGNoteId");

                    b.ToTable("GrowthNotes");
                });

            modelBuilder.Entity("MesWEB.Data.PageAccessCounter", b =>
                {
                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("PageName");

                    b.ToTable("PageAccessCounters");
                });
#pragma warning restore 612, 618
        }
    }
}
